server:
  servlet:
    context-path: /earlyautumn
  port: 80

#库配置

database:
  earlyautumn:
    driver: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/db_base?useSSL=false
